version: "3"
services:

  ktn-jobs:
    image: [IMAGE_REPO]
    # build: 
    #   context: .
    #   dockerfile: Dockerfile-server
    restart: always
    # volumes:
    #   - ./:/webapps
    #ports:
    #  - 6006:5005
    networks:
      - base-network
    command: supervisord -n -c /etc/supervisor.d/worker.conf

  ktn-jobs-nft-queue:
    image: [IMAGE_REPO]
    # build: 
    #   context: .
    #   dockerfile: Dockerfile-server
    restart: always
    # volumes:
    #   - ./:/webapps
    networks:
      - base-network
    command: celery --app worker worker -Q ktn-nft-queue -l INFO -c 4

  ktn-jobs-withdraw-royalty-queue:
    image: [IMAGE_REPO]
    # build: 
    #   context: .
    #   dockerfile: Dockerfile-server
    restart: always
    # volumes:
    #   - ./:/webapps
    networks:
      - base-network
    command: celery --app worker worker -Q ktn-withdraw-royalty -l INFO -c 4

  ktn-jobs-get-info-royalty-queue:
    image: [IMAGE_REPO]
    # build: 
    #   context: .
    #   dockerfile: Dockerfile-server
    restart: always
    # volumes:
    #   - ./:/webapps
    networks:
      - base-network
    command: celery --app worker worker -Q ktn-get-info-royalty -l INFO -c 4

  ktn-jobs-update-balance-royalty-queue:
    image: [IMAGE_REPO]
    # build: 
    #   context: .
    #   dockerfile: Dockerfile-server
    restart: always
    # volumes:
    #   - ./:/webapps
    networks:
      - base-network
    command: celery --app worker worker -Q ktn-update-balance-royalty -l INFO -c 4
    

  ktn-jobs-schedules-price:
    image:  [IMAGE_REPO]
    # build: 
    #   context: .
    #   dockerfile: Dockerfile-server
    restart: always
    # volumes:
    #   - ./:/webapps
    networks:
      - base-network
    command: python3 -u schedules/cron_price.py  

  ktn-jobs-schedules-price-cgk:
    image:  [IMAGE_REPO]
    # build: 
    #   context: .
    #   dockerfile: Dockerfile-server
    restart: always
    # volumes:
    #   - ./:/webapps
    networks:
      - base-network
    command: python3 -u schedules/cron_price_coingecko.py 

  ktn-jobs-worker:
    image:  [IMAGE_REPO]
    # build: 
    #   context: .
    #   dockerfile: Dockerfile-server
    restart: always
    # volumes:
    #   - ./:/webapps
    networks:
      - base-network
    command: celery --app worker worker -Q ktn-price-queue -l INFO -c 4  

  ktn-jobs-scan-stake-nft:
    image:  [IMAGE_REPO]
    # build: 
    #   context: .
    #   dockerfile: Dockerfile-server
    restart: always
    # volumes:
    #   - ./:/webapps
    networks:
      - base-network
    command: python3 -u schedules/cron_logs.py contract=STAKING_CONTRACT from_block=23713408 abi_path=abis/katana_staking.json handle_path=tasks handle_func=on_stake event=Stake scan_all=1

  ktn-jobs-schedule-staking:
    image:  [IMAGE_REPO]
    # build: 
    #   context: .
    #   dockerfile: Dockerfile-server
    restart: always
    # volumes:
    #   - ./:/webapps
    networks:
      - base-network
    command: python3 -u schedules/cron_staking.py

  ktn-jobs-schedules-cron-unstakeall:
    image:  [IMAGE_REPO]
    # build: 
    #   context: .
    #   dockerfile: Dockerfile-server
    restart: always
    # volumes:
    #   - ./:/webapps
    networks:
      - base-network
    command: python3 schedules/cron_logs.py contract=STAKING_CONTRACT from_block=23713408 abi_path=abis/katana_staking.json handle_path=tasks handle_func=on_un_stake_all event=UnstakeAll scan_all=0

  
  ktn-jobs-schedules-cron-withdraw:
    image:  [IMAGE_REPO]
    # build: 
    #   context: .
    #   dockerfile: Dockerfile-server
    restart: always
    # volumes:
    #   - ./:/webapps
    networks:
      - base-network
    command: python3 schedules/cron_logs.py contract=STAKING_CONTRACT from_block=23713408 abi_path=abis/katana_staking.json handle_path=tasks handle_func=on_un_stake event=Withdraw scan_all=0
  
  ktn-jobs-staking-queue:
    image:  [IMAGE_REPO]
    # build: 
    #   context: .
    #   dockerfile: Dockerfile-server
    restart: always
    # volumes:
    #   - ./:/webapps
    networks:
      - base-network
    command: celery --app worker worker -Q ktn-staking-queue -l INFO -c 4
  ktn-jobs-referral-commission-worker:
    image:  [IMAGE_REPO]
    # build: 
    #   context: .
    #   dockerfile: Dockerfile-server
    restart: always
    # volumes:
    #   - ./:/webapps
    networks:
      - base-network
    command: celery --app worker worker -Q ktn-referral-commission-queue -l INFO -c 4
  ktn-jobs-queue-worker:
    image:  [IMAGE_REPO]
    # build: 
    #   context: .
    #   dockerfile: Dockerfile-server

    restart: always
    # volumes:
    #   - ./:/webapps
    networks:
      - base-network
    command: celery --app worker worker -Q ktn-jobs-queue -l INFO -c 4
  
networks:
  base-network:
    external: true
