FROM ktn-lib:v1

RUN apk upgrade -U \
    && apk add --no-cache -u ca-certificates libffi-dev  supervisor python3-dev build-base linux-headers pcre-dev curl busybox-extras \
    && rm -rf /tmp/* /var/cache/*

RUN apk add --no-cache chromium-chromedriver


COPY requirements.txt /
RUN pip --no-cache-dir install --upgrade pip setuptools
RUN pip --no-cache-dir install -r requirements.txt

COPY conf/supervisor/ /etc/supervisor.d/
COPY . /webapps
WORKDIR /webapps
