

# File: worker-supervisor.conf

[unix_http_server]
file=/run/supervisord.sock   ; (the path to the socket file)

[supervisord]
logfile=/var/log/supervisord.log ; (main log file;default $CWD/supervisord.log)
loglevel=info                ; (log level;default info; others: debug,warn,trace)

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisord.sock ; use a unix:// URL  for a unix socket


[program:sync_refferal_with_address]
command=python sync/collection.py db=katana-dapp col=referral key_sync=address tll=-1
directory=/webapps
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:sync_refferal_with_code]
command=python sync/collection.py db=katana-dapp col=referral key_sync=code tll=-1
directory=/webapps
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:sync_user_with_address]
command=python sync/collection.py db=katana-dapp col=user key_sync=address tll=-1
directory=/webapps
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0


[program:sync_nft_detail]
command=python sync/collection.py db=katana-dapp col=nft_details key_sync=nft_id,is_show#true tll=-1
directory=/webapps
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:sync_all_nft_detail]
command=python sync/collection.py db=katana-dapp col=nft_details key_sync=is_show#true tll=-1 hset_field=nft_id
directory=/webapps
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:sync_collection_with_nft_detail]
command=python sync/collection.py db=katana-dapp col=nft_details key_sync=collection_id,is_show#true tll=-1
directory=/webapps
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:sync_collections]
command=python sync/collection.py db=katana-dapp col=collection tll=-1 hset_field=collection_id
directory=/webapps
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:sync_my_nfts]
command=python sync/collection.py db=katana-dapp col=nfts key_sync=address tll=-1 hset_field=token_id
directory=/webapps
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

